name: gcp-iam-catalog crawl

# Triggered manually via the "Run workflow" button
on:
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    timeout-minutes: 20

    environment: crawl
    concurrency:
      group: crawl

    permissions:
      contents: "write"
      id-token: "write"
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5' 

      - name: Build gcp-iam-catalog
        run: |
          go build -o gcp-iam-catalog main.go

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_USER }}
          access_token_lifetime: "1200s"

      - name: Delete iam folder
        run: |
          rm -rf iam

      - name: Run gcp-iam-catalog with crawl parameter
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=${{steps.auth.outputs.credentials_file_path}}
          ./gcp-iam-catalog -crawl

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add iam
          git commit -m "Updated IAM on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Update the remote URL to include the token for authentication
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          # Push the changes to the branch that tr
          git push origin HEAD:${{ github.ref }}
